### ISSUE TITLE
CDK deploy is failing with TooManyRequestsException 

### ISSUE THREAD

**Issue by amayaea** [aws-samples/one-observability-demo#175] opened 2022-08-03 20:04 UTC
Running `cdk deploy --context admin_role=$EKS_ADMIN_ARN Services --context dashboard_role_arn=$CONSOLE_ROLE_ARN --require-approval never
`
fails with message:
Services: creating CloudFormation changeset...
6:36:00 PM | CREATE_FAILED        | Custom::AWSCDK-EKS-KubernetesResource       | loadBalancerServiceAccount1D19AD3A
Received response status [FAILED] from custom resource. Message returned: TooManyRequestsException: Rate Exceeded.
at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)
at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:49:8)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12) (RequestId: 36cd730b-cc24-4222-a36a-ff0c219804bf)
![Screen Shot 2022-08-03 at 4 03 52 PM](https://user-images.githubusercontent.com/35306414/182698871-2709390a-0397-4890-bd8e-0dc99de5a7e9.png)

**Comment by deekob** [comment] 2022-08-10 04:22
Seeing the same behavior - most probably caused by https://github.com/aws-samples/one-observability-demo/pull/176 as it appears Lambda is getting throttled.

**Comment by awsimaya** [comment] 2022-10-24 15:59
Folks, this is an AWS internal situation where Isengard throttles resources (low containment score). Try again in an older Isengard account and you should be good. You could also test this on Event Engine. Closing this thread.

**Closed by awsimaya** 2022-10-24 15:59 UTC
